name: dental_clinic_management_system
description: "A new Flutter project."

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.5.6
  provider: ^6.1.1
  image_picker: ^1.0.5
  intl: ^0.19.0
  connectivity_plus: ^5.0.2

flutter:
  assets:
    - assets/images/Splash screen icon.png