name: dental_clinic_management_system
description: "A new Flutter project."

# Add this environment section
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ... rest of your existing dependencies ...

flutter:
  assets:
    - assets/images/Splash screen icon.png
    - assets/images/No_internet.png
  uses-material-design: true